<?php namespace Elemental\Components\Elements;


class ResponsiveImageComponent extends BaseElement {

    public function __construct() {
        $this->normalName = "Responsive Image";

        $this->fields = [
            'sml_width' => 'meta',
            'sml_height' => 'meta',
            'sml_path' => 'meta',
            'med_width' => 'meta',
            'med_height' => 'meta',
            'med_path' => 'meta',
            'lrg_width' => 'meta',
            'lrg_height' => 'meta',
            'lrg_path' => 'image',
            'alt_text' => 'text',
            'link' => 'text'
        ];


        $this->generator_rules = [
            'sml_width' => 'sometimes|required',
            'sml_height' => 'sometimes|required',
            'med_width' => 'sometimes|required',
            'med_height' => 'sometimes|required',
            'lrg_width' => 'sometimes|required',
            'lrg_height' => 'sometimes|required',
        ];

        $this->labels = [
            'sml_path' => 'Phone Size',
            'med_path' => 'Tablet Size',
            'lrg_path' => 'Desktop Size (Responsive sizes will be autogenerated)',
            'alt_text' => 'Alt Text',
            'link' => 'Link (optional)'
        ];
    }

}